### ISSUE TITLE
Jessica Jennings doesn't exist

### ISSUE THREAD

**Issue by frksn** [MicrosoftLearning/10997-O365AdministrationandTroubleshooting#1]
Lab2, Exercise 3, task 3, pt 10
"Verify that you can modify settings on the Jessica Jennings user account. Change her phone number to 555-1234, and then block her sign-in access."
Jessica doesn't exist. Should be Lindsey Gates.

**Comment by ddamir76** [comment]
This is fixed. Thanks

**Comment by frksn** [comment]
No, it is not fixed. I'm checking the lab again and Jessica is still there.
